# golangci-lint 配置文件（v2 格式）
# 文档: https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  enable:
    # 基础质量
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # 风格与规范
    - gofmt
    - goimports
    - misspell
    - revive
    # 代码质量
    - goconst
    - gocritic
    - gocyclo
    - dupl
