linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: http-services

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - errcheck      # 检查未处理的错误
    - gosimple      # 简化代码
    - govet         # 报告可疑的代码
    - ineffassign   # 检测无效的赋值
    - staticcheck   # 静态分析
    - unused        # 检查未使用的代码
    - typecheck     # 类型检查
    - gofmt         # 检查代码格式
    - goimports     # 检查 import 格式
    - misspell      # 拼写检查
    - goconst       # 检查可以提取为常量的字符串
    - gocritic      # 代码审查
    - revive        # 快速、可配置、可扩展的 linter

issues:
  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - goconst

    # 排除 vendor 目录
    - path: vendor/
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - log

output:
  sort-results: true
