# golangci-lint 配置文件（v2 格式）
# 文档: https://golangci-lint.run/usage/configuration/
version: "2"

# v2 新写法：仅保留受支持的顶层键，
# 详细配置迁移到 `settings` 下（替代 v1 的 linters-settings），
# 运行与输出相关配置建议用 CI 参数控制。

linters:
  enable:
    # 基础质量
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # 风格与规范
    - gofmt
    - goimports
    - misspell
    - revive
    # 代码质量
    - goconst
    - gocritic
    - gocyclo
    - dupl

settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow # 变量遮蔽检查过于严格

  gocyclo:
    min-complexity: 15 # 圈复杂度阈值

  dupl:
    threshold: 100 # 重复代码检测阈值

  goconst:
    min-len: 3
    min-occurrences: 3 # 字符串重复3次以上建议提取为常量

  misspell:
    locale: US

  goimports:
    local-prefixes: http-services # 本地包前缀

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
